### ISSUE TITLE
getJPXClosestToMidPoint returns frames outside requested time range

### ISSUE THREAD

**Issue by deiruch** [Helioviewer-Project/api#10]
Sometimes the `getJPXClosestToMidPoint` API returns images which are outside the requested time range. As an example, the following call requests two frames:

`http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=10&startTimes=1455552000,1455724800&endTimes=1455609600,1455782400&verbose=true&jpip=true`

The API returns two frames, the first being clearly outside the requested time range:
```
1455552000 <-- from
1455609600 <-- to
1455609610 <-- timestamp of first returned frame
```

_Note: The response of this specific call might change as new SDO data becomes available.

**Comment by deiruch** [comment]
Another example:
[http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=5&startTimes=1361020401,1361059767,1361079450,1361118816,1361138499,1361177865&endTimes=1361040084,1361079450,1361099133,1361138499,1361158182,1361197548](http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=5&startTimes=1361020401,1361059767,1361079450,1361118816,1361138499,1361177865&endTimes=1361040084,1361079450,1361099133,1361138499,1361158182,1361197548) returns the following three frames:

```
1361020401-1361040084 <-- range 1

1361050205 <-- result 1

1361059767-1361079450 <-- range 2
1361079450-1361099133 <-- range 3

1361109245 <-- result 2

1361118816-1361138499 <-- range 4
1361138499-1361158182 <-- range 5

1361168285 <-- result 3

1361177865-1361197548 <-- range 6
```

This query is for data from 2013. So the results probably won't change anymore.

**Comment by ddialer** [comment]
Fixed

**Comment by deiruch** [comment]
Thanks! The fix helped.

**Comment by deiruch** [comment]
I just got some reports that this bug still occurs:

[http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=10&startTimes=1456701651,1456702137,1456702380,1456702866,1456703109,1456703595&endTimes=1456701894,1456702380,1456702623,1456703109,1456703352,1456703838](http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=10&startTimes=1456701651,1456702137,1456702380,1456702866,1456703109,1456703595&endTimes=1456701894,1456702380,1456702623,1456703109,1456703352,1456703838)

returns frame 1456702030, which is outside the requested time ranges.

**Comment by ddialer** [comment]
Fixed. Looks like movie was generated before I applied fix two weeks ago. After re-generating movie dates is in a right range

**Comment by deiruch** [comment]
It's still there... :(

I reproduced the problem with this query: [http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=10&jpip=true&verbose=true&startTimes=1456966810,1456967386,1456969546,1456971742,1456973938,1456974142,1456976134,1456978294,1456980490,1456982686,1456984882,1456984942,1456987042,1456989238,1456991434,1456993630&endTimes=1456966811,1456967387,1456969547,1456971743,1456973939,1456975942,1456976135,1456978295,1456980491,1456982687,1456984883,1456986742,1456987043,1456989239,1456991435,1456993631&verbose=true](http://api.helioviewer.org/v2/getJPXClosestToMidPoint/?sourceId=10&jpip=true&verbose=true&startTimes=1456966810,1456967386,1456969546,1456971742,1456973938,1456974142,1456976134,1456978294,1456980490,1456982686,1456984882,1456984942,1456987042,1456989238,1456991434,1456993630&endTimes=1456966811,1456967387,1456969547,1456971743,1456973939,1456975942,1456976135,1456978295,1456980491,1456982687,1456984883,1456986742,1456987043,1456989239,1456991435,1456993631&verbose=true)

`{"message":null,"uri":"jpip:\/\/helioviewer.org:8090\/movies\/SDO_AIA_171_F2016-03-03T01.00.10Z_T2016-03-03T08.27.11Z.jpx","frames":[null,null,1456970518,null,null,null,null,1456979518,null,null,null,null,null,1456990318,null,null]}`

But 1456990318 is outside the requested time ranges.

**Comment by deiruch** [comment]
This seems to have worked. Thanks!
