### ISSUE TITLE
Connection resets and "500 Internal Server error"

### ISSUE THREAD

**Issue by deiruch** [Helioviewer-Project/api#11]
The API currently often replies with connection resets and "500 Internal Server Error"s instead of actual data. The same requests succeeded yesterday.

Unfortunately the server still no provides details when an internal server error occurs.

Am I doing anything wrong? Can I diagnose the problem? Can you check the logs?

**Comment by ddialer** [comment]
@deiruch,
I restarted jpip server.

Inside logs I fount next two types of errors. it is strange, but files is exist on the server and I have no problems to open it.

first error. The error only with this file. After some research I find out that this file is just regular jp2 image and not are video. Is It suppose to be like this?:
```
/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:163: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_AIA_1600_F2012-07-10T00.00.00Z_T2012-07-13T00.00.00ZB180L.jpx' can not be opened
```

Second error. Many different files. I look into files and everything looks fine. Is it possible that something with esajpip server?:
```
2016-03-08 14:23:31,652: /esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:124: ERROR: Impossible to open file: '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-08T11.46.55Z_T2016-03-08T14.26.22Z.jpx'... 
2016-03-08 14:23:31,652: /esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-08T11.46.55Z_T2016-03-08T14.26.22Z.jpx' can not be read 
2016-03-08 14:23:31,652: /esajpip_0.3/esajpip/esajpip/src/client_manager.cc:161: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-08T11.46.55Z_T2016-03-08T14.26.22Z.jpx' can not be read 
```

**Comment by bogdanni** [comment]
I've committed a change to log the reason for failure. Could you please install it?
For the record, we are running this server for months at a time with no such errors.

**Comment by deiruch** [comment]
Works again nicely.

**Comment by ddialer** [comment]
@bogdanni, just installed new update for jpip.

**Comment by deiruch** [comment]
This is occurring again. All my requests fail with a "500 Internal Server Error". Repro: Download the current beta release of JHelioviewer (3.0.5) and start it. http://www.jhelioviewer.org/download_archive.html)

**Comment by bogdanni** [comment]
Hopefully now there is more info in the logs.

**Comment by ddialer** [comment]
restarted service again.

I found this type of errors:
```
2016-03-10 13:02:41,951: The channel 161 has been opened for the image '/mnt/data/jp2/movies/SDO_AIA_AIA_304_F2014-03-08T00.00.00Z_T2016-03-09T00.00.00ZB172800L.jpx' 
2016-03-10 13:02:42,024: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:222: ERROR: A new data chunk could not be generated 

The channel 3700 has been opened for the image '/mnt/data/jp2/movies/SDO_AIA_AIA_193_F2016-03-13T20.00.34Z_T2016-03-13T23.00.34ZB60L.jpx' 
2016-03-14 03:43:48,731: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:190: ERROR: The server can not process the request 

2016-03-14 10:13:11,245: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:124: ERROR: Impossible to open file: '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-13T13.31.46Z_T2016-03-13T21.31.46ZCMP.jpx'... 
2016-03-14 10:13:11,245: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-13T13.31.46Z_T2016-03-13T21.31.46ZCMP.jpx' can not be read 
2016-03-14 10:13:11,245: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:161: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_171_F2016-03-13T13.31.46Z_T2016-03-13T21.31.46ZCMP.jpx' can not be read 
```

@bogdanni, I sent you full log as well.

**Comment by bogdanni** [comment]
@ddialer, are you sure the commit with extra logging was checked out, compiled and installed? I expected a fourth error in the sequence file_manager -> index_manager -> client_manager.
My guess is that misuse of the very limited API offered leads to files not being closed on the error path, thus the process hits some limit of opened files.

@deiruch, in our experience, the requested region (size+offset) should be clipped to be within the requested resolution size, otherwise it leads to those errors: "A new data chunk could not be generated".

**Comment by deiruch** [comment]
@bogdanni Do you have an example of an invalid request? JHV only generates requests where fsiz=rsiz. If I read the spec correctly, this should always work - regardless of the values used, because rsiz is specified in a coordinate system of size fsiz.

**Comment by ddialer** [comment]
@bogdanni, sorry, buy mistake compiled from old source. I just tried to compile new source and I got this error: https://github.com/Helioviewer-Project/JHelioviewer-SWHV/issues/1

**Comment by ddialer** [comment]
Recompiled from new source.

After closer examination of:
```
The channel 3700 has been opened for the image '/mnt/data/jp2/movies/SDO_AIA_AIA_193_F2016-03-13T20.00.34Z_T2016-03-13T23.00.34ZB60L.jpx' 
2016-03-14 03:43:48,731: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:190: ERROR: The server can not process the request 
```

Looks like file api.helioviewer.org/jp2/movies/SDO_AIA_AIA_304_F2014-03-08T00.00.00Z_T2016-03-09T00.00.00ZB172800L.jpx is just regular JP2 image and not are video. Is it suppose to be like this or that can be are problem?

**Comment by bogdanni** [comment]
Most likely can be a problem, the server uses file extension to determine the way it parses the file.

**Comment by bogdanni** [comment]
@deiruch, I'm just saying that if the client makes requests where rsiz+roff are outside of fsiz, the esajpip server may issue errors like that, no matter what the standard says. SWHV JHV has code to clip, e.g.
https://github.com/Helioviewer-Project/JHelioviewer-SWHV/blob/master/src/jhv/src/org/helioviewer/jhv/viewmodel/imagedata/SubImage.java#L11

**Comment by deiruch** [comment]
@bogdanni This is the relevant piece of code from JHV:

```
		query.setField("fsiz", _width + "," + _height + ",closest");
		query.setField("rsiz", _width + "," + _height);
		query.setField("roff", "0,0");
```

As far as I understand, rsiz+roff are impossible to lie outside fsiz. Or did I not understand your suggestion? Perhaps an example of an offending request would be helpful.

**Comment by bogdanni** [comment]
Simon, that looks fine. Could be an older client (v2) that led to those errors.

**Comment by deiruch** [comment]
This problem is still ocurring. Is there anything in the logs?

**Comment by ddialer** [comment]
@deiruch, we are just switched to the new API v3 and server was rebooted. I just finished linking all the directories and now everything should work normal.

**Comment by bogdanni** [comment]
This broke users of the older API like SWHV (http://swhv.oma.be/download/) or classical JHV (2.2).

**Comment by dmueller3000** [comment]
Confirmed: Right now, the classical JHV (2.2), which is still used by many people, unfortunately does not work anymore. It would be great if this could be fixed, at least for a transition period.

**Comment by ddialer** [comment]
I just tested SWHV from the link you provided and its seems working fine. 
I tried to download older JHV 2.1 and 2.2.1 and both give me an error that application is damaged and the download size is just 3Mb for both of them.

**Comment by bogdanni** [comment]
@ddialer, with SWHV you have to try to load data from the GSFC server in the dialog box for new layer.

**Comment by bogdanni** [comment]
@ddialer, with JHV 2.2, if you are on a Mac, you have to set in System Preferences -> Security & Privacy -> General -> Allow apps downloaded from: Anywhere. The app is not signed.

**Comment by dmueller3000** [comment]
The file size of JHV 2.2.1 is indeed small (3.6 MB) as all libraries are loaded at start-up rather than being included in the executable.
> both give me an error that application is damaged
> 

Could it be that you are on OS X and your security settings are not set to ‘Allow apps downloaded from anywhere’? In 2012, when JHV 2.2.1 was released, we did not sign the application with a Mac Developer Key yet, which necessitates this change of security settings. In the default setting, OS X indeed complains the the application is ‘damaged’ - which is, however, not the case.

Hope that helps!

Daniel

**Comment by dmueller3000** [comment]
I can confirm Bogdan's comment: Using the about-to-be-released version of JHV (http://swhv.oma.be/download/, http://www.jhelioviewer.org), users cannot load data from the GSFC server! :-(

**Comment by ddialer** [comment]
Should be fixed. Problem was on apache redirect rule.

**Comment by dmueller3000** [comment]
@ddialer : Thanks! Unfortunately, I still get a "connection reset" error on both JHV 2.2.1 and 2.10. The entries of the Observatory/Instrument/Dector fields, however, are visible now, so the problem might have moved to a different place (JPIP server?).

![image](https://cloud.githubusercontent.com/assets/9073862/14147913/b2897118-f69d-11e5-9fa5-d415efef99ec.png)

**Comment by deiruch** [comment]
This happens with JHV 3.0.5 as well. It's at the JPIP server level.

**Comment by ddialer** [comment]
Restarted JPIP server. Server was overloaded with connections.

@bogdanni, there is new type of errors I found in the log
```
2016-03-30 12:20:27,535: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:204: ERROR: The code-stream does not include any PLT marker 
2016-03-30 12:20:27,535: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/STEREO_A_SECCHI_EUVI_284_F2011-10-11T23.45.00Z_T2011-10-12T07.45.00ZCMP.jpx' can not be read 
2016-03-30 12:20:27,535: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:161: ERROR: The image file '/mnt/data/jp2/movies/STEREO_A_SECCHI_EUVI_284_F2011-10-11T23.45.00Z_T2011-10-12T07.45.00ZCMP.jpx' can not be read 
```

**Comment by wafels** [comment]
I am running JHV 2.10.0 Rev 6818 using GSFC with no issues. Thanks!

**Comment by bogdanni** [comment]
@ddialer, some JP2 files made with IDL were not transcoded when ingested into the HV server.

**Comment by wafels** [comment]
I agree.  In the normal course of jp2gen processing, that should not have
happened.

@ddialer, If you have a list of the affected files, I can remake them.

@bogdanni, do you have tools to test if a file has been transcoded or not?
That would be a good verification step to run.

**Comment by ddialer** [comment]
@wafels, I'm not sure what files is effected. but there is two movie files that giving that errors:
STEREO_A_SECCHI_EUVI_284_F2011-10-11T23.45.00Z_T2011-10-12T07.45.00ZCMP.jpx
STEREO_A_SECCHI_EUVI_284_F2011-10-17T15.45.00Z_T2011-10-17T23.45.00ZCMP.jpx
How I understand the files may be inside that time ranges.

The problem I have right now is I getting wall of this errors and they all open new connection and never closing the previous until server is overloaded.

**Comment by bogdanni** [comment]
@wafels, `hvJP2K/bin/hv_jp2_verify` does all the conformance checks.

It's a bit difficult to use since the IDL JP2 files have the XML with a terminating NULL which is formally forbidden by the XML standard (but not truly a problem for the use in HV/JHV). I will try to come up with a recipe for installation.

Note also `hvJP2K/bin/hv_jp2_transcode` which allows to use an original `kdu_transcode` as distributed (the one you are using now is specially modified to output JP2 files) and is also able to take out the NULL at the end of XML.

**Comment by dmueller3000** [comment]
@ddialer : Thanks a lot! I have checked JHV 2.10.0, 3.0.5 and 2.2.1, and all work like a charm with the GSFC server now.

**Comment by bogdanni** [comment]
@ddialer : your server is down again. Could you please check out the latest revision from 'esajpip-SWHV', I may have solved the problem. I believe sockets were leaked, our server was also experiencing some errors from a client connected from an apparently ESA IP address...

**Comment by ddialer** [comment]
@bogdanni Done. JPIP server restarted and updated

**Comment by deiruch** [comment]
The server again is refusing all JPIP connections at the moment...

**Comment by ddialer** [comment]
@deiruch, I restarted jpip server. Inside logs, I found this error. Before the error, everything is looking fine
```
2016-07-27 10:40:30,240: New connection from xxx.xxx.xxx.xxx:xxxxxx [6] 
2016-07-27 10:40:30,240: /esajpip/src/esa_jpip_server.cc:151: ERROR: Problems accepting a new connection 
2016-07-27 10:40:30,241: Closing the connection [6] 
2016-07-27 10:40:30,241: Closing the connection [6] from child 
```

**Comment by bogdanni** [comment]
Briefly looking through the code, I'm not sure the logic is correct on the error path.
My opinion is that all the networking code should be ripped apart from this server and frontend-ed by a real HTTP server.

**Comment by ddialer** [comment]
@bogdanni, I restarted the jpip server. Transcode seems to work fine. But a few days ago I received some other strange errors. I'm not sure if this errors caused by jpip or our server.

```
esajpip[43012]: segfault at 0 ip 00007efcc87dce68 sp 00007efcc4bccac0 error 4 in libjpipcore.so.1.0[7efcc87b8000+2d000]
traps: esajpip[58385] trap divide error ip:7efcc89f6875 sp:7efcc4bccc40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[58405] trap divide error ip:7efcc89f6875 sp:7efc7bffdc40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[7756] trap divide error ip:7efcc89f6875 sp:7efcbb7fcc40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[36702] trap divide error ip:7efcc89f6875 sp:7efcba7fac40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[58411] trap divide error ip:7efcc89f6875 sp:7efcc13c5c40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[20121] trap divide error ip:7efcc89f6875 sp:7efcbaffbc40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[20149] trap divide error ip:7efcc89f6875 sp:7efcb9ff9c40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[58396] trap divide error ip:7efcc89f6875 sp:7efcb27fac40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
traps: esajpip[5042] trap divide error ip:7efcc89f6875 sp:7efcaaffbc40 error:0 in libjpipnet.so.1.0[7efcc89e8000+18000]
```

**Comment by bogdanni** [comment]
That's new.
Can you identify the line numbers from the addresses? Not so sure how to do it, with some ELF utils?
libjpipcore.so.1.0[7efcc87b8000+2d000]
libjpipnet.so.1.0[7efcc89e8000+18000]

**Comment by bogdanni** [comment]
Maybe something like the following:
addr2line -e esajpip 00007efcc87dce68
addr2line -e esajpip 7efcc89f6875

**Comment by ddialer** [comment]
both addresses return "??:0"

**Comment by bogdanni** [comment]
I still receive 500s here. Are there new errors? Maybe try to run it inside gdb?
I believe there are two issues, null pointer in libjpipcore and division by zero libjpipnet.

**Comment by ddialer** [comment]
I just get back to logs and there is two type of errors:

```
2016-10-21 10:13:48,241: esajpip/esajpip/src/data/file.h:149: ERROR: Impossible to open file: 'jp2/movies/SDO_AIA_171_F2016-03-26T20.52.41Z_T2016-03-29T20.37.22ZCMP.jpx': No such file or directory 
2016-10-21 10:13:48,241: esajpip/esajpip/src/jpeg2000/file_manager.cc:124: ERROR: Impossible to open file: 'jp2/movies/SDO_AIA_171_F2016-03-26T20.52.41Z_T2016-03-29T20.37.22ZCMP.jpx'... 
2016-10-21 10:13:48,241: esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file 'jp2/movies/SDO_AIA_171_F2016-03-26T20.52.41Z_T2016-03-29T20.37.22ZCMP.jpx' can not be read 
2016-10-21 10:13:48,241: esajpip/esajpip/src/client_manager.cc:159: ERROR: The image file 'jp2/movies/SDO_AIA_171_F2016-03-26T20.52.41Z_T2016-03-29T20.37.22ZCMP.jpx' can not be read 
```
And new one:
```
2016-10-21 10:13:19,155: esajpip/esajpip/src/esa_jpip_server.cc:162: ERROR: The new socket can not be sent to the child process
```

**Comment by ddialer** [comment]
I fixed the missing file error. And restarted JPIP again. May it will resolve the socket error

**Comment by bogdanni** [comment]
Still there. Anything changed in the environment, like the OS etc. ?

**Comment by bogdanni** [comment]
Funny that SWAP works. I still suspect transcoding problems, should get a message about PLT missing.

**Comment by ddialer** [comment]
Strange. I don't see any errors in the logs. No, nothing changed. We only rebooted server this monday. Also I sent email to you with full JPIP log for last two hours

**Comment by ddialer** [comment]
Hold on. maybe you are right. seems there is problem with transcoding

**Comment by bogdanni** [comment]
Yes, at least some files are not transcoded:

2016-10-21 09:40:22,511: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:204: ERROR: The code-stream does not include any PLT marker 
2016-10-21 09:40:22,511: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_304_F2016-10-19T00.00.00Z_T2016-10-21T12.57.46ZB600L.jpx' can not be read 
2016-10-21 09:40:22,512: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:159: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_304_F2016-10-19T00.00.00Z_T2016-10-21T12.57.46ZB600L.jpx' can not be read 

2016-10-21 10:24:20,758: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:204: ERROR: The code-stream does not include any PLT marker 
2016-10-21 10:24:20,759: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_94_F2016-10-19T13.56.58Z_T2016-10-21T13.56.58ZB1800L.jpx' can not be read 
2016-10-21 10:24:20,759: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:159: ERROR: The image file '/mnt/data/jp2/movies/SDO_AIA_94_F2016-10-19T13.56.58Z_T2016-10-21T13.56.58ZB1800L.jpx' can not be read 

2016-10-21 10:24:32,016: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/file_manager.cc:204: ERROR: The code-stream does not include any PLT marker 
2016-10-21 10:24:32,016: /tmp/esajpip_0.3/esajpip/esajpip/src/jpeg2000/index_manager.cc:51: ERROR: The image file '/mnt/data/jp2/movies/SOHO_LASCO_C2_white-light_F2016-10-19T13.56.58Z_T2016-10-21T13.56.58ZB1800L.jpx' can not be read 
2016-10-21 10:24:32,016: /tmp/esajpip_0.3/esajpip/esajpip/src/client_manager.cc:159: ERROR: The image file '/mnt/data/jp2/movies/SOHO_LASCO_C2_white-light_F2016-10-19T13.56.58Z_T2016-10-21T13.56.58ZB1800L.jpx' can not be read

**Comment by ddialer** [comment]
I'm reinserting some data. may take couple hours to finish. There was an transcode issue

**Comment by bogdanni** [comment]
1. I will modify asap hvJP2K such that you can run more easily `hv_jp2_verify` and `hv_jp2_transcode` at your site.
1. I'm worried about the new errors you got inside esajpip. Maybe a good idea to run it under gdb for a while if you cannot trace back the line number?

**Comment by ddialer** [comment]
@bogdanni is it just SDO data need to be transcoded or other sources as well?

**Comment by ddialer** [comment]
1. Where can I find that hv_jp2_verify and hv_jp2_transcode?
2. That error starts appearing when we had a server issues this Sunday. and I'm not sure it was caused by JPIP or something else. And can you explain to me how I can run jpip under gdb? never done it before

**Comment by bogdanni** [comment]
> Where can I find that hv_jp2_verify and hv_jp2_transcode?

https://github.com/Helioviewer-Project/hvJP2K

>  And can you explain to me how I can run jpip under gdb? never done it before

In some screen(1):
$ gdb ./esajpip
(gdb) r

**Comment by bogdanni** [comment]
> is it just SDO data need to be transcoded or other sources as well?

SOHO LASCO also.

**Comment by ddialer** [comment]
I reinserted all SDO and SOHO data that was broken. should work now

**Comment by dgarciabriseno** [comment]
Closing since last comment indicates this was fixed.
